version: '3'
services:
  app:
    build: .
    ports:
      - '2000:2000'
    command:  sh -c "yarn install && yarn run dev"
    volumes:
      - ~/projects/backend:/usr/app/
    environment:
      PORT: '2000'